// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWS7foZoVEEAIC_dR3BQGr-ngVUSDl70',
    appId: '1:285106660310:web:d6c6f4f777bc1e89907a77',
    messagingSenderId: '285106660310',
    projectId: 'closer-5d0ca',
    authDomain: 'closer-5d0ca.firebaseapp.com',
    storageBucket: 'closer-5d0ca.appspot.com',
    measurementId: 'G-RMRLWVDDC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cPzUkOi0HJdWTvEtYZyvMHea1HzbC6Y',
    appId: '1:285106660310:android:b18e8969d6cb8b1c907a77',
    messagingSenderId: '285106660310',
    projectId: 'closer-5d0ca',
    storageBucket: 'closer-5d0ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrfQQBhF9kmN1K3591vuY_3CO89utQivM',
    appId: '1:285106660310:ios:b249a0254e068a2f907a77',
    messagingSenderId: '285106660310',
    projectId: 'closer-5d0ca',
    storageBucket: 'closer-5d0ca.appspot.com',
    iosClientId: '285106660310-dm7hpgik5hsgc8cl8smsu6gkcqa4sv7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrfQQBhF9kmN1K3591vuY_3CO89utQivM',
    appId: '1:285106660310:ios:b249a0254e068a2f907a77',
    messagingSenderId: '285106660310',
    projectId: 'closer-5d0ca',
    storageBucket: 'closer-5d0ca.appspot.com',
    iosClientId: '285106660310-dm7hpgik5hsgc8cl8smsu6gkcqa4sv7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.y',
  );
}
